### ISSUE TITLE
Cleanup VO translation

### ISSUE THREAD

**Issue by bbockelm** [opensciencegrid/topology#1]
Looking here: https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/CMS.yaml

Some thoughts:
1.  Remove redundant contact entries on conversion.
2. Remove the contact IDs.  We only need the IDs for cases where we can filter via the web.
3. Remove information (such as the list of resources) that can be calculated in other places.  Since the resource YAML will include the membership info, we don't also need it here too.
4. Remove defaults entries.

This should drastically simplify the VO entries.

**Comment by matyasselmeci** [comment]
It would be nice if we could get rid of some of the redundancies in the data structure. Here's a mockup of what I'm thinking of: https://gist.github.com/matyasselmeci/04a38d2c64834abf02210d8948726718

**Comment by brianhlin** [comment]
Let's also drop `null` attributes like we did for the resource groups. 

And @matyasselmeci, in your example why are there OASIS managers but `UseOASIS` is `false`? That doesn't seem to make sense to me.

**Comment by matyasselmeci** [comment]
I copied the ATLAS yaml file from Derek's previous commit and made the changes by hand. If the new data doesn't make sense, it's because the old data didn't make sense :)

**Comment by matyasselmeci** [comment]
I don't think there's a separate attrib for temporarily disabling OASIS so it makes sense not to delete the managers in case they plan to use OASIS in the future.

**Comment by brianhlin** [comment]
Well yea, I mean if `Managers: null`, `OASISRepoURLs: null`, and `UseOASIS: false`, we can exclude the section.

**Comment by matyasselmeci** [comment]
I've got a few functions in `converters/convertlib.py` that might be useful for the transformations.

**Comment by matyasselmeci** [comment]
How does this look? https://github.com/matyasselmeci/topology/commit/9578b330703d361bf9f1547664baacb9a30792bc

I still need to fix up `ReportingGroups`: each VO should only have a list of the groups it belongs to; the `Contacts` and `FQANs` of each group should be in a separate file.

**Comment by djw8605** [comment]
Looks great to me!

**Comment by bbockelm** [comment]
LGTM!

**Comment by matyasselmeci** [comment]
OK, I think we're done here.
