### ISSUE TITLE
Hosted CE is listed as non-production, and not found for GRACC

### ISSUE THREAD

**Issue by djw8605** [opensciencegrid/topology#1198]
@efajardo @matyasselmeci 

The hosted-ce34.grid.uchicago.edu is showing up in GRACC, a lot.  But, it's listed as non-production in the topology, and therefore doesn't show up in the topology listing.  Can we change this to production so the usage can be mapped?

https://github.com/opensciencegrid/topology/blob/1abc8527d8b983c3d4d789d3a2b0701c43bc8251/topology/University%20of%20California%20San%20Diego/COMET/CometVirtualCluster.yaml#L2

**Comment by matyasselmeci** [comment]
Note that production/non-production is set on a per-ResourceGroup basis, so we would be changing the status of all the resources in that file. Is that OK?

**Comment by djw8605** [comment]
Unsure about the other resources.  And edgar is out for a few days.  But, we are missing usage!

**Comment by matyasselmeci** [comment]
If it's urgent then I can make the change; if it turns out to be wrong, Edgar can revert it when he gets back.

**Comment by djw8605** [comment]
Sounds good to me!  Make the change.

**Comment by efajardo** [comment]
I think there is something funky I thin that hostedCE is for actual production use from Comet but no the virtual cluster. So do I have to create another site?  I think @mmascher set this up

**Comment by matyasselmeci** [comment]
You don't have to create an entire new site, just a new ResourceGroup (i.e. yaml file).

**Comment by matyasselmeci** [comment]
Just an explanation: `Production: True/False` converts to the `GridType` attribute in the XML, which is either "OSG Production Resource" i.e. it reports to the production collector, or "OSG Integration Test Bed Resource" i.e. it reports to the ITB collector (do we still have one?) It's per-ResourceGroup in the YAML because it's per-ResourceGroup in the XML.

**Comment by matyasselmeci** [comment]
Is this issue solved?

**Comment by brianhlin** [comment]
This is very stale and I don't think hosted-ce34 exists anymore. It doesn't show up in the list of prod Hosted CEs (though it does exist in DNS both at the `opensciencegrid.org` and `grid.uchicago.edu` domains). Closing.
