### ISSUE TITLE
Filter VOs based on OASIS status

### ISSUE THREAD

**Issue by bbockelm** [opensciencegrid/topology#16]
The filtering in MyOSG for OASIS attributes for VO queries is not replicated to the current VO responses.

We should implement this for OASIS attributes _and_ the active attributes (if we don't already).  I see we can additionally filter on support center ... it's not clear if that's necessary.

**Comment by DrDaveD** [comment]
Oasis also depends on &sort_key=name which is also not working.

**Comment by djw8605** [comment]
Your XML parser requires sorting?  Isn't XML by definition can be out of order and still be correct?

**Comment by DrDaveD** [comment]
The parser doesn't require sorting, but the output of the program needs to be sorted.  It could do its own sorting, but it's more convenient if it already comes sorted.

**Comment by matyasselmeci** [comment]
Filtering by oasis should be good:
https://my-itb.opensciencegrid.org/vosummary/xml?&oasis=on&oasis_value=1

**Comment by matyasselmeci** [comment]
Which xml does sort_key=name sort, and which specific attribute does it sort by?

**Comment by DrDaveD** [comment]
> Filtering by oasis should be good

Yes it is, but now there's a new problem in that at least sometimes the nesting of "DN" is many levels deep, for example:
```
<OASIS><UseOASIS>True</UseOASIS><Managers><Manager><Name>Arthur Kreymer</Name><DNs><DN><DN><DN><DN><DN><DN><DN><DN><DN><DN>/DC=org/DC=doegrids/OU=People/CN=Arthur E Kreymer 261310</DN><DN>/DC=com/DC=DigiCert-Grid/O=Open Science Grid/OU=People/CN=Arthur Kreymer 965</DN></DN></DN></DN></DN></DN></DN></DN></DN></DN></DNs></Manager></Managers>
```

> Which xml does sort_key=name sort, and which specific attribute does it sort by?

I have only seen it used on the vosummary, and there it sorts by VO name.

**Comment by DrDaveD** [comment]
Now it looks like it is sorted on the vo name by default so the sorting is fine, I just have the nested DN problem.

**Comment by matyasselmeci** [comment]
Fixed the nested DN problem.

**Comment by DrDaveD** [comment]
Ok, the oasis users of my-itb.opensciencegrid.org are all happy.  

I'm not given a button close this issue, so you please do it.

**Comment by matyasselmeci** [comment]
OK, thanks!
