### ISSUE TITLE
Add new IGWN token issuer for LIGO VO

### ISSUE THREAD

**Issue by duncanmmacleod** [opensciencegrid/topology#2747]
The LIGO VO topology includes the https://scitokens.org/ligo token issuer. AFAIK we are transitioning to https://scitokens.org/igwn, which will include some new scopes etc for internal use.

Can we update the LIGO VO topology file to reference that issuer? I am listed as a VO Manager, so should I be the one to propose a Pull Request that implements that?

cc @josh-willis @rdt12 @jjg-123

**Comment by brianhlin** [comment]
@duncanmmacleod we keep track of collaboration token issuers here https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/LIGO.yaml#L40-L43. Optionally, you can also add a specific subject here: https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/CMS.yaml#L5.

However, this is mainly for keeping track of pilot token mappings for CEs. If this issuer is just for internal user, I'm not sure that we need to track that issuer.

**Comment by duncanmmacleod** [comment]
Thanks @brianhlin, I have a patch for the LIGO.yaml topology file ready to go but want to understand the pilot tokens first. I presume we would want to update the pilots to use the new issuer as well, but defer to @astroclark or @rdt12 for confirmation.

**Comment by jasoncpatton** [comment]
I think it's these lines that need changing and/or appending to:
https://github.com/opensciencegrid/topology/blob/e34adf29bb06a87e624e5c4cc6a6c9ceebd56939/virtual-organizations/LIGO.yaml#L81-L89
