### ISSUE TITLE
Add KSU-Beocat-CE1 resource

### ISSUE THREAD

**Issue by jasoncpatton** [opensciencegrid/topology#2888]
This resource is missing from topology. I'm guessing `KSU-Beocat-CE1` is a replacement for `BEOCAT-SLATE`?
https://github.com/opensciencegrid/topology/blob/master/topology/Kansas%20State%20University/Beocat/BEOCAT-SLATE.yaml

**Comment by brianhlin** [comment]
@jdost321 this looks like maybe a new-style CE that needs to be registered?

**Comment by jdost321** [comment]
Here's the pr: https://github.com/opensciencegrid/topology/pull/2889
