### ISSUE TITLE
Store all sources under src/ dir

### ISSUE THREAD

**Issue by brianhlin** [opensciencegrid/topology#30]
To improve usability for our end-users, we should move all the sources under a `src/` dir so that we have the following structure

```
projects/
src/
topology/
.gitignore
.travis.yml
virtual-organizations/
README.md
template-*.yaml
```

**Comment by brianhlin** [comment]
Yes but as @bbockelm mentioned, we want to keep the option open for deployment via heroku. If we separate the source into a different repo, how does that work? @djw8605?

**Comment by djw8605** [comment]
I'm not sure how that will work.  Even now, what we have won't work on heroku due to using git from the system to retrieve contact information.

Since we can't use git from the system to download the topology information, I'm not entirely sure how we would get it.

**Comment by matyasselmeci** [comment]
Will Heroku check out Git submodules in the repo?

**Comment by djw8605** [comment]
A quick google says no:

> Using submodules for builds on Heroku is only supported for builds triggered with git pushes. Builds created with the API do not resolve submodules. This is also the case for GitHub sync.

We use GitHub sync.  We do not `git push` directly to heroku.

**Comment by brianhlin** [comment]
In the future, the contact info may go through COManage so that git dependency could very possibly go away.

**Comment by matyasselmeci** [comment]
This is not my preferred solution, but it's better than nothing. Mind if I just do this?

**Comment by brianhlin** [comment]
Go for it

**Comment by matyasselmeci** [comment]
This has been pushed to production and works now.
