### ISSUE TITLE
Clean up GOC resources

### ISSUE THREAD

**Issue by brianhlin** [opensciencegrid/topology#63]
There are quite a few resources associated with the [GOC](https://github.com/opensciencegrid/topology/tree/master/topology/Indiana%20University) that should be either removed entirely if they won't have an effect on GRACC accounting (cc @djw8605 ) or deactivated and disabled.

**Comment by matyasselmeci** [comment]
Is this done with #92 or is there more to do?

**Comment by brianhlin** [comment]
Nope, it's done
