### ISSUE TITLE
Add entries for services migrated from GOC

### ISSUE THREAD

**Issue by matyasselmeci** [opensciencegrid/topology#72]
The following things are now hosted at University of Nebraska-Omaha:

- topology server
- osg-display
- software repos

@djw8605 , anything else?

We should create entries for them. Use the new "Topology Server" service type for the topology server; the other services already have service type entries.

**Comment by matyasselmeci** [comment]
In case anything moved to other places, we'll need entries for them, too.

**Comment by brianhlin** [comment]
- @jdost321 will know about the factories
- @efajardo and @ShawnMckee should know about the networking hosts
- @sthapa and @rynge will know about XD login and flock
- @zvada and @DrDaveD know about the OASIS hosts

**Comment by matyasselmeci** [comment]
We decommissioned these or moved them to tiger.
